server {
    listen 80;
    server_name {name};

    root /var/www/phpmyadmin;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Logs séparés
    access_log /var/www/phpmyadmin/logs/access.log;
    error_log  /var/www/phpmyadmin/logs/error.log;
}
