# setup.conf
# Configuration pour le script d'installation et de setup du serveur Ubuntu

# ----- Serveur -----
# Nouveau nom d'hôte du serveur
HOSTNAME="monserveur"

# ----- Compte administrateur système -----
ADMIN_USERNAME="adminuser"
ADMIN_PASSWORD="MotDePasseAdmin123"
ADMIN_EMAIL="mail@example.com"

# ----- Compte administrateur MariaDB -----
DB_ADMIN_USERNAME="dbadmin"
DB_ADMIN_PASSWORD="MotDePasseDB123"

# ----- Accès phpMyAdmin -----
PHPMA_USERNAME="phpmauser"
PHPMA_PASSWORD="MotDePassePhpma123"
PHPMA_DOMAIN="monserveur.fr"

# ----- Compte FTP admin web -----
FTP_ADMIN_USERNAME="ftpadmin"
FTP_ADMIN_PASSWORD="MotDePasseFTP123"

# ----- Configuration SSH -----
SSH_PORT=55

# ----- Rotation des logs -----
LOG_RETENTION_DAYS=30

# ----- Sauvegarde des sites -----
BACKUP_LOCAL_PATH=/var/server_backups
BACKUP_KEEP_LOCAL=7
BACKUP_KEEP_REMOTE=14
BACKUP_INCLUDE_ETC=true
BACKUP_TIME="03:00"
BACKUP_SFTP_HOST=host.save.com
BACKUP_SFTP_PORT=22
BACKUP_SFTP_USER="sftp_user"
BACKUP_SFTP_PASS="sftp_password"
BACKUP_LOG_FILE="/var/log/backup.log"
