# setup.conf
# Configuration pour le script d'installation et de setup du serveur Ubuntu

# ----- Serveur -----
# Nouveau nom d'hôte du serveur
HOSTNAME="monserveur"

# ----- Compte administrateur système -----
ADMIN_USERNAME="adminuser"
ADMIN_PASSWORD="MotDePasseAdmin123"
ADMIN_EMAIL="mail@example.com"

# ----- Compte administrateur MariaDB -----
DB_ADMIN_USERNAME="dbadmin"
DB_ADMIN_PASSWORD="MotDePasseDB123"

# ----- Accès phpMyAdmin -----
PHPMA_USERNAME="phpmauser"
PHPMA_PASSWORD="MotDePassePhpma123"
PHPMA_DOMAIN="monserveur.fr"

# ----- Compte FTP admin web -----
FTP_ADMIN_USERNAME="ftpadmin"
FTP_ADMIN_PASSWORD="MotDePasseFTP123"

# ----- Configuration SSH -----
SSH_PORT=55

# ----- Rotation des logs -----
LOG_RETENTION_DAYS=30
